In [1]:
import pandas as pd
import numpy as np

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
import pandas as pd

# Load dataset
dataset = pd.read_csv("Preprocessed_car_predict.csv")

# Randomly sample 10,000 rows
dataset = dataset.sample(n=1000, random_state=42)

# Save reduced dataset
dataset.to_csv("reduced_dataset.csv", index=False)

In [4]:
dataset

,make,model,year,mileage,engine_hp,transmission,fuel_type,drivetrain,body_type,exterior_color,interior_color,owner_count,accident_history,seller_type,condition,trim,vehicle_age,mileage_per_year,brand_popularity,price
987231,19,1,2018,94000,181,0,1,0,3,2,3,5,2,0,2,1,7,13428.571429,0.040148,19226.82
79954,18,68,2021,94190,464,1,1,1,5,0,3,2,2,0,0,5,4,23547.500000,0.040210,60435.02
567130,1,7,2020,76853,325,1,0,0,5,3,2,1,2,1,1,5,5,15370.600000,0.040022,28708.28
500891,19,0,2017,109290,223,1,2,2,3,4,0,5,2,0,2,5,8,13661.250000,0.040148,18938.64
55399,7,39,2019,40701,212,0,2,0,4,4,3,3,2,1,2,2,6,6783.500000,0.039842,18487.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
914398,8,9,2021,65349,170,0,2,2,4,0,2,1,2,0,0,5,4,16337.250000,0.039754,27227.54
189053,16,80,2009,220415,322,0,1,0,5,5,2,5,0,0,2,0,16,13775.937500,0.039794,7112.87
47977,13,78,2020,135697,400,1,1,2,4,4,1,4,1,0,2,0,5,27139.400000,0.040133,41265.44
600785,12,92,2014,191197,97,1,2,0,5,4,0,5,2,1,2,3,11,17381.545455,0.040484,1500.00
67400,13,29,2024,16362,425,1,1,0,4,3,2,2,2,0,2,2,1,16362.000000,0.040133,70796.08

In [5]:
dataset.columns

Index(['make', 'model', 'year', 'mileage', 'engine_hp', 'transmission',
       'fuel_type', 'drivetrain', 'body_type', 'exterior_color',
       'interior_color', 'owner_count', 'accident_history', 'seller_type',
       'condition', 'trim', 'vehicle_age', 'mileage_per_year',
       'brand_popularity', 'price'],
      dtype='object')

In [6]:
independent=dataset[['make', 'model', 'year', 'mileage', 'engine_hp', 'transmission',
       'fuel_type', 'drivetrain', 'body_type', 'exterior_color',
       'interior_color', 'owner_count', 'accident_history', 'seller_type',
       'condition', 'trim', 'vehicle_age', 'mileage_per_year',
       'brand_popularity']]

In [7]:
dependent=dataset[['price']]

In [8]:
#Model Selection
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [9]:
#Linear Regressor
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)
y_predict=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.9093906723985539

In [16]:
#Standard Scaler
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
from sklearn.svm import SVR
regressor=SVR(kernel="linear")
regressor.fit(X_train,y_train) 
y_predict=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.1263053644841179

In [10]:
#Random Forest
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=100, criterion ='poisson', random_state=0)
regressor.fit(X_train,y_train)
y_predict=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.937597169397364

In [11]:
#Decision Tree
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)
from sklearn.tree import DecisionTreeRegressor, plot_tree
regressor=DecisionTreeRegressor(criterion ='poisson', splitter='random')
regressor.fit(X_train,y_train)
y_predict=regressor.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_predict)
print(r_score)

0.8275890034353778

In [14]:
from sklearn.feature_selection import SelectKBest, f_regression

def selectkbest(independent, dependent, n):
    test = SelectKBest(score_func=f_regression, k=n)
    fit1 = test.fit(independent, dependent.values.ravel())
    selectk_features = fit1.transform(independent)
    return selectk_features

kbest = selectkbest(independent, dependent, 3)

In [15]:
from sklearn.feature_selection import SelectKBest, f_classif

# Select top 5 features
selector = SelectKBest(score_func=f_classif, k=7)
X_new = selector.fit_transform(independent, dependent)

# Get selected feature names
selected_features = independent.columns[selector.get_support()]
print(selected_features)

Index(['make', 'year', 'mileage', 'engine_hp', 'owner_count', 'vehicle_age',
       'mileage_per_year'],
      dtype='object')